export const userSubscribedClasses = [
  {
    id: "cls_001",
    title: "Frontend Development Bootcamp",
    description: "Learn HTML, CSS, JavaScript, and React to build dynamic user interfaces.",
    instructor: "Jane Doe",
    enrolledDate: "2025-05-01",
    progress: 72, // percentage
    isCompleted: false,
    category: "Web Development",
    imageUrl: "/images/image_1.jpg",
  },
  {
    id: "cls_001",
    title: "Frontend Development Bootcamp",
    description: "Learn HTML, CSS, JavaScript, and React to build dynamic user interfaces.",
    instructor: "Jane Doe",
    enrolledDate: "2025-05-01",
    progress: 72, // percentage
    isCompleted: false,
    category: "Web Development",
    imageUrl: "/images/image_1.jpg",
  },
  {
    id: "cls_002",
    title: "Python for Beginners",
    description: "Start from scratch and master the fundamentals of Python programming.",
    instructor: "John Smith",
    enrolledDate: "2025-04-15",
    progress: 100,
    isCompleted: true,
    category: "Programming",
    imageUrl: "/images/image_4.jpg",
  },
  {
    id: "cls_003",
    title: "UI/UX Design Principles",
    description: "Explore the basics of design, user psychology, and tools like Figma.",
    instructor: "Emily Carter",
    enrolledDate: "2025-03-22",
    progress: 45,
    isCompleted: false,
    category: "Design",
    imageUrl: "/images/image_2.jpg",
  },
  {
    id: "cls_0010",
    title: "UI/UX Design Principles",
    description: "Explore the basics of design, user psychology, and tools like Figma.",
    instructor: "Emily Carter",
    enrolledDate: "2025-03-22",
    progress: 100,
    isCompleted: true,
    category: "Design",
    imageUrl: "/images/image_7.jpg",
  },
  {
    id: "cls_0010",
    title: "UI/UX Design Principles",
    description: "Explore the basics of design, user psychology, and tools like Figma.",
    instructor: "Emily Carter",
    enrolledDate: "2025-03-22",
    progress: 100,
    isCompleted: true,
    category: "Design",
    imageUrl: "/images/image_2.jpg",
  },
];
